# ~/.tmuxinator/default.yml
 
# Set var "WDIR" to workdir
<% if @args[0] %>
<% WDIR=@args[0] %> 
<% else %>
<% WDIR=ENV["PWD"] %>
<% end %>

name: <%= WDIR.split('/').last  %>
root: <%= @args[0] %>

windows:
  - null:
      layout: 75f2,333x87,0,0{233x87,0,0,28,99x87,234,0,29}
      panes:
        - editor:
          - "nvim"
          - ":NvimTreeToggle"
        - #empty, it will just run zsh
